title: "CARVE: Cade Andgreg Risc-V Emulator"
email: info@chemicaldevelopment.us
description: >-
  Cade Andgreg Risc-V Emulator
baseurl: ""
url: "carve.chemicaldevelopment.us"
twitter_username: chemicaldevelopment
github_username:  chemicaldevelopment

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
- src/
- readme.md
- Makefile
- Gemfile
- Gemfile.lock
- .jekyll-cache/